### ISSUE TITLE
window reference introduced in 2.5.8 crashes Node

### ISSUE THREAD

**Issue by mporkola** [willmcpo/body-scroll-lock#51]
Hi, and thanks for this lib!

The reference to `window` introduced in https://github.com/willmcpo/body-scroll-lock/pull/45 crashes Node when e.g. server rendering. Yes, it could be avoided by dynamically importing `body-scroll-lock` only on browser, but I believe it would make sense to just guard against this with a `typeof window` check or something similar.

I could make a PR next week. I guess it doesn't matter which result the passive event listener feature check gives when running on Node?

**Comment by willmcpo** [comment]
Makes sense Nikko. Happy for you to submit a PR.

Thanks

**Comment by willpox** [comment]
Fixed

**Comment by artem-zur** [comment]
Hi guys!

Seems like problem still exists in last plugin version ...

Do I need to create a new issue ?
